In [1]:
import cme.decision_models.confidence_accumulation as ca
import numpy as np
import scipy.stats as stats
import pandas as pd
import seaborn as sns
import numpyro as npy
import numpyro.distributions as dist

In [2]:
max_samples, max_RT = 400, 40

In [3]:
n_states, start_width, delta, measurement_prob,  = 101, 11, 0.5, 0.8
I, J = 20, 100

In [4]:
threshold, measurement_prob, mu, sigma = 1, 1, np.asarray([[1]]), np.asarray([[2]])
model_type = "Markov"
transition_type="RT"

In [5]:
t_s = stats.uniform(delta,max_RT/delta).rvs((I,max_samples))
t_s.shape

(20, 400)

In [6]:
t_s

array([[18.26580445,  1.12335004, 67.21563574, ..., 60.68577252,
        79.68778353, 31.95390927],
       [46.48124839, 68.53126985, 66.8347374 , ..., 67.68748165,
        52.50864585, 51.72970506],
       [45.36970655, 25.79788881, 33.27246654, ..., 23.72543972,
        53.80399982,  6.02587061],
       ...,
       [10.49537306, 19.59768936, 66.11051069, ..., 12.61463577,
         3.60315712, 41.67107652],
       [23.90471164, 31.58587918, 39.84477097, ..., 26.81812776,
        72.30823558, 77.98442878],
       [27.97290689, 71.45867571, 48.48381403, ..., 30.46547166,
        14.80703184, 57.19274033]])

In [7]:
intensity_matrix = ca.get_intensity_matrix(n_states, mu, sigma, model_type=model_type)
phi_0 = ca._get_initial_state(n_states, start_width,model_type=model_type, prior_type="Centered")
intensity_matrix, phi_0

(Array([[[[-2. ,  0.5,  0. , ...,  0. ,  0. ,  0. ],
          [ 2. , -2. ,  0.5, ...,  0. ,  0. ,  0. ],
          [ 0. ,  1.5, -2. , ...,  0. ,  0. ,  0. ],
          ...,
          [ 0. ,  0. ,  0. , ..., -2. ,  0.5,  0. ],
          [ 0. ,  0. ,  0. , ...,  1.5, -2. ,  2. ],
          [ 0. ,  0. ,  0. , ...,  0. ,  1.5, -2. ]]]], dtype=float64),
 Array([[[[0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.09090909],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ]]]], dtype=float64))

In [8]:
Mc, Mw, Mn = ca._get_measurement_matrix(n_states, threshold, prob=measurement_prob, model_type = model_type)
Mc

Array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float64)

In [9]:
t = t_s #np.asarray([[4.5]]) #
phi_t = ca.perform_state_transition(intensity_matrix=intensity_matrix, RT_s=t, RA_s = None, delta=delta, 
Mc = Mc, Mn = Mn, Mw = Mw, phi_0=phi_0, 
transition_type=transition_type, likelihood_type="SINGLE")
phi_t.shape

(20, 400, 101, 1)

In [10]:
phi_t

Array([[[[3.48476707e-28],
         [2.09500891e-27],
         [1.10465363e-26],
         ...,
         [6.73699507e-06],
         [4.89629589e-06],
         [2.38854094e-06]],

        [[4.20898009e-66],
         [8.24973217e-65],
         [1.42989366e-63],
         ...,
         [5.33145874e-43],
         [9.26673211e-44],
         [1.39950556e-44]],

        [[1.76598628e-25],
         [6.52272550e-25],
         [1.70028885e-24],
         ...,
         [1.45032662e-01],
         [4.23311203e-01],
         [3.16170315e-01]],

        ...,

        [[4.41855554e-25],
         [1.65578078e-24],
         [4.42890993e-24],
         ...,
         [1.38720772e-01],
         [3.90145564e-01],
         [2.89735717e-01]],

        [[2.06791688e-26],
         [7.49490719e-26],
         [1.88749112e-25],
         ...,
         [1.47872107e-01],
         [4.41923191e-01],
         [3.31251585e-01]],

        [[4.65853160e-25],
         [2.07065535e-24],
         [7.28829495e-24],
         ...,
         [1.04324804e-02],
         [1.54427869e-02],
         [9.99066948e-03]]],


       [[[1.42978439e-24],
         [5.64337967e-24],
         [1.64972311e-23],
         ...,
         [8.82213363e-02],
         [2.02621165e-01],
         [1.45314978e-01]],

        [[1.43921304e-25],
         [5.30271974e-25],
         [1.37614986e-24],
         ...,
         [1.45693142e-01],
         [4.27243123e-01],
         [3.19334918e-01]],

        [[1.87164423e-25],
         [6.91807611e-25],
         [1.80574032e-24],
         ...,
         [1.44813121e-01],
         [4.22034063e-01],
         [3.15144168e-01]],

        ...,

        [[1.64216276e-25],
         [6.05993829e-25],
         [1.57710122e-24],
         ...,
         [1.45286280e-01],
         [4.24804217e-01],
         [3.17370974e-01]],

        [[1.03363204e-24],
         [3.97283708e-24],
         [1.11055104e-23],
         ...,
         [1.17662171e-01],
         [3.01778284e-01],
         [2.20760861e-01]],

        [[1.09612712e-24],
         [4.22562903e-24],
         [1.18725090e-23],
         ...,
         [1.14550382e-01],
         [2.90266421e-01],
         [2.11900037e-01]]],


       [[[1.46308868e-24],
         [5.80902647e-24],
         [1.71480957e-23],
         ...,
         [8.16225886e-02],
         [1.82890355e-01],
         [1.30545851e-01]],

        [[6.27324269e-26],
         [3.07335768e-25],
         [1.24264568e-24],
         ...,
         [1.15503165e-03],
         [1.29988724e-03],
         [7.69259098e-04]],

        [[6.10151885e-25],
         [2.66938425e-24],
         [9.17645662e-24],
         ...,
         [1.45508143e-02],
         [2.26664485e-02],
         [1.48747401e-02]],

        ...,

        [[2.21115126e-26],
         [1.13236703e-25],
         [4.86206525e-25],
         ...,
         [3.97735113e-04],
         [4.01997381e-04],
         [2.28277586e-04]],

        [[9.28528486e-25],
         [3.55209207e-24],
         [9.84942458e-24],
         ...,
         [1.22368082e-01],
         [3.19785520e-01],
         [2.34675584e-01]],

        [[3.03583983e-41],
         [4.65719696e-40],
         [6.87631438e-39],
         ...,
         [2.63758038e-18],
         [5.52331479e-19],
         [1.07476879e-19]]],


       ...,


       [[[9.31007600e-34],
         [8.61031397e-33],
         [7.44935199e-32],
         ...,
         [3.29637031e-11],
         [1.25125319e-11],
         [4.01541511e-12]],

        [[1.21233318e-27],
         [6.95858388e-27],
         [3.46357840e-26],
         ...,
         [2.25651916e-05],
         [1.79001958e-05],
         [9.12694864e-06]],

        [[2.08725799e-25],
         [7.72611766e-25],
         [2.02186005e-24],
         ...,
         [1.44356386e-01],
         [4.19418365e-01],
         [3.13045015e-01]],

        ...,

        [[1.14860562e-31],
         [9.10547725e-31],
         [6.64160777e-30],
         ...,
         [3.17575822e-09],
         [1.48412064e-09],
         [5.53906523e-10]],

        [[2.30788200e-49],
         [5.82302370e-48],
         [1.42827276e-46],
         ...,
         [5.12201444e-26],
         [6.32939523e-27],
         [7.50688666e-28]],

        [[1.42604094e-24],
         [5.79098697e-24],
         [1.77339741e-23],
         ...,
         [5.84402660e-02],
         [1.19391927e-01],
         [8.36427828e-02]]],


       [[[2.44259695e-26],
         [1.24574228e-25],
         [5.31939081e-25],
         ...,
         [4.39823718e-04],
         [4.48843815e-04],
         [2.55865280e-04]],

        [[4.28416709e-25],
         [1.91320278e-24],
         [6.78086020e-24],
         ...,
         [9.43852482e-03],
         [1.37677396e-02],
         [8.86936222e-03]],

        [[1.31710186e-24],
         [5.41889308e-24],
         [1.69444908e-23],
         ...,
         [4.70652553e-02],
         [9.13256816e-02],
         [6.32702263e-02]],

        ...,

        [[9.68572746e-26],
         [4.65432177e-25],
         [1.83216619e-24],
         ...,
         [1.81951837e-03],
         [2.15243079e-03],
         [1.29677206e-03]],

        [[7.75313477e-26],
         [2.83845628e-25],
         [7.28157554e-25],
         ...,
         [1.46939586e-01],
         [4.35162924e-01],
         [3.25738732e-01]],

        [[2.83847589e-26],
         [1.03091644e-25],
         [2.60623094e-25],
         ...,
         [1.47756219e-01],
         [4.41002685e-01],
         [3.30496977e-01]]],


       [[[1.49913137e-25],
         [7.06006931e-25],
         [2.70164143e-24],
         ...,
         [2.89926463e-03],
         [3.62073560e-03],
         [2.22224538e-03]],

        [[8.94445337e-26],
         [3.27903223e-25],
         [8.43252569e-25],
         ...,
         [1.46726408e-01],
         [4.33746933e-01],
         [3.24590367e-01]],

        [[1.32959318e-24],
         [5.19687989e-24],
         [1.49462257e-23],
         ...,
         [9.93076931e-02],
         [2.37638015e-01],
         [1.71730327e-01]],

        ...,

        [[3.23929903e-25],
         [1.46850444e-24],
         [5.32061437e-24],
         ...,
         [6.81291557e-03],
         [9.49136750e-03],
         [6.03170544e-03]],

        [[4.93596629e-30],
         [3.44979536e-29],
         [2.17831303e-28],
         ...,
         [1.13704262e-07],
         [6.40757218e-08],
         [2.70340395e-08]],

        [[6.66109943e-25],
         [2.52032672e-24],
         [6.85651889e-24],
         ...,
         [1.32073214e-01],
         [3.59721785e-01],
         [2.65783061e-01]]]], dtype=float64)

In [11]:
phi_t.sum(axis=-2, keepdims=True).sum()

Array(8000., dtype=float64)

In [12]:
[phi_i_j.squeeze().sum() for phi_i in phi_t for phi_i_j in phi_i ]

[Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),

In [13]:
phi_t[0,0,:,0]

Array([3.48476707e-28, 2.09500891e-27, 1.10465363e-26, 5.83067696e-26,
       3.02621286e-25, 1.54125912e-24, 7.69918406e-24, 3.77111453e-23,
       1.81058107e-22, 8.51833549e-22, 3.92593163e-21, 1.77191168e-20,
       7.82907282e-20, 3.38534245e-19, 1.43209421e-18, 5.92471805e-18,
       2.39628879e-17, 9.47179423e-17, 3.65755989e-16, 1.37930280e-15,
       5.07783220e-15, 1.82426616e-14, 6.39335913e-14, 2.18494594e-13,
       7.27885111e-13, 2.36284946e-12, 7.47140261e-12, 2.30040740e-11,
       6.89429908e-11, 2.01051699e-10, 5.70310361e-10, 1.57311060e-09,
       4.21809374e-09, 1.09914133e-08, 2.78259799e-08, 6.84219174e-08,
       1.63375208e-07, 3.78732580e-07, 8.52229399e-07, 1.86119896e-06,
       3.94449209e-06, 8.11178442e-06, 1.61863967e-05, 3.13394361e-05,
       5.88784277e-05, 1.07344748e-04, 1.89941447e-04, 3.26247651e-04,
       5.44073897e-04, 8.81180973e-04, 1.38644429e-03, 2.11993316e-03,
       3.15133701e-03, 4.55625463e-03, 6.41009675e-03, 8.77973059e-03,
       1.17134678e-02, 1.52304745e-02, 1.93110518e-02, 2.38893903e-02,
       2.88502825e-02, 3.40308685e-02, 3.92278646e-02, 4.42099752e-02,
       4.87344617e-02, 5.25662359e-02, 5.54974637e-02, 5.73655333e-02,
       5.80673800e-02, 5.75685390e-02, 5.59058813e-02, 5.31837089e-02,
       4.95636778e-02, 4.52497583e-02, 4.04700427e-02, 3.54575544e-02,
       3.04322453e-02, 2.55860744e-02, 2.10725057e-02, 1.70010465e-02,
       1.34367109e-02, 1.04036683e-02, 7.89191472e-03, 5.86562916e-03,
       4.27193566e-03, 3.04902816e-03, 2.13294784e-03, 1.46265746e-03,
       9.83367014e-04, 6.48292642e-04, 4.19165039e-04, 2.65850313e-04,
       1.65428435e-04, 1.01015795e-04, 6.05428216e-05, 3.56228396e-05,
       2.05862545e-05, 1.17155906e-05, 6.73699507e-06, 4.89629589e-06,
       2.38854094e-06], dtype=float64)

stats.multinomial(n=1, p=phi_t[0,0,:,0]).rvs()

In [14]:
phi_t

Array([[[[3.48476707e-28],
         [2.09500891e-27],
         [1.10465363e-26],
         ...,
         [6.73699507e-06],
         [4.89629589e-06],
         [2.38854094e-06]],

        [[4.20898009e-66],
         [8.24973217e-65],
         [1.42989366e-63],
         ...,
         [5.33145874e-43],
         [9.26673211e-44],
         [1.39950556e-44]],

        [[1.76598628e-25],
         [6.52272550e-25],
         [1.70028885e-24],
         ...,
         [1.45032662e-01],
         [4.23311203e-01],
         [3.16170315e-01]],

        ...,

        [[4.41855554e-25],
         [1.65578078e-24],
         [4.42890993e-24],
         ...,
         [1.38720772e-01],
         [3.90145564e-01],
         [2.89735717e-01]],

        [[2.06791688e-26],
         [7.49490719e-26],
         [1.88749112e-25],
         ...,
         [1.47872107e-01],
         [4.41923191e-01],
         [3.31251585e-01]],

        [[4.65853160e-25],
         [2.07065535e-24],
         [7.28829495e-24],
         ...,
         [1.04324804e-02],
         [1.54427869e-02],
         [9.99066948e-03]]],


       [[[1.42978439e-24],
         [5.64337967e-24],
         [1.64972311e-23],
         ...,
         [8.82213363e-02],
         [2.02621165e-01],
         [1.45314978e-01]],

        [[1.43921304e-25],
         [5.30271974e-25],
         [1.37614986e-24],
         ...,
         [1.45693142e-01],
         [4.27243123e-01],
         [3.19334918e-01]],

        [[1.87164423e-25],
         [6.91807611e-25],
         [1.80574032e-24],
         ...,
         [1.44813121e-01],
         [4.22034063e-01],
         [3.15144168e-01]],

        ...,

        [[1.64216276e-25],
         [6.05993829e-25],
         [1.57710122e-24],
         ...,
         [1.45286280e-01],
         [4.24804217e-01],
         [3.17370974e-01]],

        [[1.03363204e-24],
         [3.97283708e-24],
         [1.11055104e-23],
         ...,
         [1.17662171e-01],
         [3.01778284e-01],
         [2.20760861e-01]],

        [[1.09612712e-24],
         [4.22562903e-24],
         [1.18725090e-23],
         ...,
         [1.14550382e-01],
         [2.90266421e-01],
         [2.11900037e-01]]],


       [[[1.46308868e-24],
         [5.80902647e-24],
         [1.71480957e-23],
         ...,
         [8.16225886e-02],
         [1.82890355e-01],
         [1.30545851e-01]],

        [[6.27324269e-26],
         [3.07335768e-25],
         [1.24264568e-24],
         ...,
         [1.15503165e-03],
         [1.29988724e-03],
         [7.69259098e-04]],

        [[6.10151885e-25],
         [2.66938425e-24],
         [9.17645662e-24],
         ...,
         [1.45508143e-02],
         [2.26664485e-02],
         [1.48747401e-02]],

        ...,

        [[2.21115126e-26],
         [1.13236703e-25],
         [4.86206525e-25],
         ...,
         [3.97735113e-04],
         [4.01997381e-04],
         [2.28277586e-04]],

        [[9.28528486e-25],
         [3.55209207e-24],
         [9.84942458e-24],
         ...,
         [1.22368082e-01],
         [3.19785520e-01],
         [2.34675584e-01]],

        [[3.03583983e-41],
         [4.65719696e-40],
         [6.87631438e-39],
         ...,
         [2.63758038e-18],
         [5.52331479e-19],
         [1.07476879e-19]]],


       ...,


       [[[9.31007600e-34],
         [8.61031397e-33],
         [7.44935199e-32],
         ...,
         [3.29637031e-11],
         [1.25125319e-11],
         [4.01541511e-12]],

        [[1.21233318e-27],
         [6.95858388e-27],
         [3.46357840e-26],
         ...,
         [2.25651916e-05],
         [1.79001958e-05],
         [9.12694864e-06]],

        [[2.08725799e-25],
         [7.72611766e-25],
         [2.02186005e-24],
         ...,
         [1.44356386e-01],
         [4.19418365e-01],
         [3.13045015e-01]],

        ...,

        [[1.14860562e-31],
         [9.10547725e-31],
         [6.64160777e-30],
         ...,
         [3.17575822e-09],
         [1.48412064e-09],
         [5.53906523e-10]],

        [[2.30788200e-49],
         [5.82302370e-48],
         [1.42827276e-46],
         ...,
         [5.12201444e-26],
         [6.32939523e-27],
         [7.50688666e-28]],

        [[1.42604094e-24],
         [5.79098697e-24],
         [1.77339741e-23],
         ...,
         [5.84402660e-02],
         [1.19391927e-01],
         [8.36427828e-02]]],


       [[[2.44259695e-26],
         [1.24574228e-25],
         [5.31939081e-25],
         ...,
         [4.39823718e-04],
         [4.48843815e-04],
         [2.55865280e-04]],

        [[4.28416709e-25],
         [1.91320278e-24],
         [6.78086020e-24],
         ...,
         [9.43852482e-03],
         [1.37677396e-02],
         [8.86936222e-03]],

        [[1.31710186e-24],
         [5.41889308e-24],
         [1.69444908e-23],
         ...,
         [4.70652553e-02],
         [9.13256816e-02],
         [6.32702263e-02]],

        ...,

        [[9.68572746e-26],
         [4.65432177e-25],
         [1.83216619e-24],
         ...,
         [1.81951837e-03],
         [2.15243079e-03],
         [1.29677206e-03]],

        [[7.75313477e-26],
         [2.83845628e-25],
         [7.28157554e-25],
         ...,
         [1.46939586e-01],
         [4.35162924e-01],
         [3.25738732e-01]],

        [[2.83847589e-26],
         [1.03091644e-25],
         [2.60623094e-25],
         ...,
         [1.47756219e-01],
         [4.41002685e-01],
         [3.30496977e-01]]],


       [[[1.49913137e-25],
         [7.06006931e-25],
         [2.70164143e-24],
         ...,
         [2.89926463e-03],
         [3.62073560e-03],
         [2.22224538e-03]],

        [[8.94445337e-26],
         [3.27903223e-25],
         [8.43252569e-25],
         ...,
         [1.46726408e-01],
         [4.33746933e-01],
         [3.24590367e-01]],

        [[1.32959318e-24],
         [5.19687989e-24],
         [1.49462257e-23],
         ...,
         [9.93076931e-02],
         [2.37638015e-01],
         [1.71730327e-01]],

        ...,

        [[3.23929903e-25],
         [1.46850444e-24],
         [5.32061437e-24],
         ...,
         [6.81291557e-03],
         [9.49136750e-03],
         [6.03170544e-03]],

        [[4.93596629e-30],
         [3.44979536e-29],
         [2.17831303e-28],
         ...,
         [1.13704262e-07],
         [6.40757218e-08],
         [2.70340395e-08]],

        [[6.66109943e-25],
         [2.52032672e-24],
         [6.85651889e-24],
         ...,
         [1.32073214e-01],
         [3.59721785e-01],
         [2.65783061e-01]]]], dtype=float64)

def test(a,d):
    print(a.shape)
    return a

np.apply_over_axes(test, phi_t, axes=[0]).shape
#np.apply_along_axis(test, -2, phi_t).shape

In [15]:
import jax
rng = jax.random.key(1)
rng

Array((), dtype=key<fry>) overlaying:
[0 1]

In [16]:
states_t = dist.Multinomial(total_count=1, probs=phi_t[...,0]).sample(key=(rng:=jax.random.split(rng)[0]))
states_t.shape

(20, 400, 101)

[stats.multinomial(n=1, p=phi_i_j.squeeze()).rvs() for phi_i in phi_t for phi_i_j in phi_i ]

states_t1 = np.array([stats.multinomial(n=1, p=phi_i_j.squeeze()).rvs() for phi_i in phi_t for phi_i_j in phi_i ])
states_t1.shape

In [17]:
np.argwhere(states_t)

array([[  0,   0,  67],
       [  0,   1,  54],
       [  0,   2,  82],
       ...,
       [ 19, 397,  82],
       [ 19, 398,  72],
       [ 19, 399,  99]])

In [18]:
np.argwhere(states_t).T

array([[  0,   0,   0, ...,  19,  19,  19],
       [  0,   1,   2, ..., 397, 398, 399],
       [ 67,  54,  82, ...,  82,  72,  99]])

In [19]:
state_final = np.argwhere(states_t)
state_final

array([[  0,   0,  67],
       [  0,   1,  54],
       [  0,   2,  82],
       ...,
       [ 19, 397,  82],
       [ 19, 398,  72],
       [ 19, 399,  99]])

In [20]:
n_states - threshold

100

In [21]:
t_s.shape

(20, 400)

In [22]:
state_final >= n_states - threshold - 1

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       ...,
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

np.where((state_final < threshold - 1) | (state_final >= n_states - threshold - 1))

In [23]:
RA = np.select([
    state_final[:,[-1]] < threshold - 1,
    state_final[:,[-1]] >= n_states - threshold - 1
], [0,1], default = np.nan)#[:,-1]
RA.shape

(8000, 1)

In [24]:
t_s.flatten()[:,None].shape

(8000, 1)

In [25]:
state_final.shape

(8000, 3)

In [26]:
(t_s.flatten()[:,None]).shape

(8000, 1)

In [27]:
Response = np.hstack((state_final, RA, t_s.flatten()[:,None]*delta))
Response

array([[  0.        ,   0.        ,  67.        ,          nan,
          9.13290222],
       [  0.        ,   1.        ,  54.        ,          nan,
          0.56167502],
       [  0.        ,   2.        ,  82.        ,          nan,
         33.60781787],
       ...,
       [ 19.        , 397.        ,  82.        ,          nan,
         15.23273583],
       [ 19.        , 398.        ,  72.        ,          nan,
          7.40351592],
       [ 19.        , 399.        ,  99.        ,   1.        ,
         28.59637016]])

In [28]:
df_res = pd.DataFrame(Response, columns=["I", "J", "state", "RA", "RT"])
df_res

         I      J  state   RA         RT
0      0.0    0.0   67.0  NaN   9.132902
1      0.0    1.0   54.0  NaN   0.561675
2      0.0    2.0   82.0  NaN  33.607818
3      0.0    3.0   85.0  NaN  23.500515
4      0.0    4.0  100.0  1.0  25.099545
...    ...    ...    ...  ...        ...
7995  19.0  395.0   99.0  1.0  38.474195
7996  19.0  396.0   48.0  NaN   1.078763
7997  19.0  397.0   82.0  NaN  15.232736
7998  19.0  398.0   72.0  NaN   7.403516
7999  19.0  399.0   99.0  1.0  28.596370

[8000 rows x 5 columns]

In [29]:
df_res.dropna().groupby(["I"]).count()

        J  state   RA   RT
I
0.0   122    122  122  122
1.0   145    145  145  145
2.0   126    126  126  126
3.0   125    125  125  125
4.0   141    141  141  141
5.0   134    134  134  134
6.0   143    143  143  143
7.0   113    113  113  113
8.0   131    131  131  131
9.0   127    127  127  127
10.0  111    111  111  111
11.0  116    116  116  116
12.0  124    124  124  124
13.0  133    133  133  133
14.0  117    117  117  117
15.0  127    127  127  127
16.0  135    135  135  135
17.0  112    112  112  112
18.0  114    114  114  114
19.0  118    118  118  118

In [30]:
df_res = df_res.dropna()
get_id = (df_res.groupby(["I"]).count() < J)[["J"]].query("J == True").index.values
get_id

array([], dtype=float64)

In [36]:
df_sample = df_res.groupby(["I"]).nth(slice(None, J)).drop("J", axis=1)
df_sample

         I  state   RA         RT
4      0.0  100.0  1.0  25.099545
8      0.0  100.0  1.0  29.210640
11     0.0  100.0  1.0  38.810567
13     0.0   99.0  1.0  27.287228
19     0.0   99.0  1.0  23.331122
...    ...    ...  ...        ...
7923  19.0  100.0  1.0  29.869043
7930  19.0   99.0  1.0  39.757442
7936  19.0  100.0  1.0  26.893303
7942  19.0  100.0  1.0  35.292134
7946  19.0   99.0  1.0  29.989155

[2000 rows x 4 columns]

In [37]:
df_sample.groupby(["I"]).count()

      state   RA   RT
I
0.0     100  100  100
1.0     100  100  100
2.0     100  100  100
3.0     100  100  100
4.0     100  100  100
5.0     100  100  100
6.0     100  100  100
7.0     100  100  100
8.0     100  100  100
9.0     100  100  100
10.0    100  100  100
11.0    100  100  100
12.0    100  100  100
13.0    100  100  100
14.0    100  100  100
15.0    100  100  100
16.0    100  100  100
17.0    100  100  100
18.0    100  100  100
19.0    100  100  100